# Generated by Django 5.1 on 2025-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('regime_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_id', models.CharField(max_length=100, unique=True)),
                ('regime_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
            ],
        ),
    ]
