# Generated by Django 5.1 on 2025-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
            ],
        ),
    ]
