# Generated by Django 5.1 on 2025-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_section_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='regime_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='schedule_id',
            field=models.CharField(max_length=100),
        ),
    ]
