# Generated by Django 5.1 on 2025-03-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_permissions_regimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('radio', 'Radio'), ('picklist', 'Pick List'), ('variant-a', 'Variant A'), ('variant-b', 'Variant B')], max_length=20)),
                ('guidance', models.TextField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=20, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='app1.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(blank=True, null=True)),
                ('end_process', models.BooleanField(default=False)),
                ('current_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_routes', to='app1.question')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_routes', to='app1.question')),
            ],
        ),
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_id', models.CharField(max_length=100, unique=True)),
                ('regime_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=100, unique=True)),
                ('schedule_name', models.CharField(max_length=255)),
                ('regimes', models.ManyToManyField(related_name='schedules', to='app1.regime')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=100, unique=True)),
                ('section_name', models.CharField(max_length=255)),
                ('schedules', models.ManyToManyField(related_name='sections', to='app1.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Regimes',
        ),
        migrations.RemoveField(
            model_name='screenquestion',
            name='parent_screen',
        ),
        migrations.DeleteModel(
            name='ScreenRouting',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='permission',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.regime'),
        ),
        migrations.AddField(
            model_name='permission',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.schedule'),
        ),
        migrations.AddField(
            model_name='questionrouting',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='app1.section'),
        ),
        migrations.AddField(
            model_name='permission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.section'),
        ),
        migrations.DeleteModel(
            name='ScreenQuestion',
        ),
        migrations.AddConstraint(
            model_name='questionrouting',
            constraint=models.UniqueConstraint(fields=('section', 'current_question', 'answer_value'), name='unique_routing_rule'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user_id', 'regime', 'schedule', 'section')},
        ),
    ]
