# Generated by Django 5.1 on 2025-03-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_permission_question_questionrouting_regime_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='schedules',
        ),
        migrations.AddField(
            model_name='section',
            name='schedule_id',
            field=models.CharField(default='Schedule_1', max_length=100),
        ),
    ]
