# Generated by Django 5.1 on 2025-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_schedule_regime_id_alter_schedule_schedule_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionrouting',
            name='unique_routing_rule',
        ),
        migrations.RemoveField(
            model_name='questionrouting',
            name='end_process',
        ),
        migrations.RemoveField(
            model_name='questionrouting',
            name='section',
        ),
        migrations.AddField(
            model_name='questionrouting',
            name='section_id',
            field=models.CharField(default='section_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionrouting',
            name='current_question',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionrouting',
            name='next_question',
            field=models.CharField(default='Q1', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='questionrouting',
            constraint=models.UniqueConstraint(fields=('section_id', 'current_question', 'answer_value'), name='unique_routing_rule'),
        ),
    ]
