# Generated by Django 5.1 on 2025-03-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_questionrouting_unique_routing_rule_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionRouting',
            new_name='Routing',
        ),
    ]
