# Generated by Django 5.1 on 2025-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_routing_options_routing_order_in_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertable',
            name='answer',
            field=models.JSONField(default=list),
        ),
    ]
