# Generated by Django 5.1 on 2025-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_section_schedules_section_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='regimes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='regime_id',
            field=models.CharField(default='Regime_1', max_length=100),
        ),
    ]
