# Generated by Django 5.1 on 2025-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_schedule_regimes_schedule_regime_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user_id', 'regime_id', 'schedule_id', 'section_id')},
        ),
        migrations.AddField(
            model_name='permission',
            name='regime_id',
            field=models.CharField(default='Regime_1', max_length=100),
        ),
        migrations.AddField(
            model_name='permission',
            name='schedule_id',
            field=models.CharField(default='Schedule_1', max_length=100),
        ),
        migrations.AddField(
            model_name='permission',
            name='section_id',
            field=models.CharField(default='Section_1', max_length=100),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='regime',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='section',
        ),
    ]
