# Generated by Django 5.1 on 2025-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_answertable_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerbasic',
            name='answer',
            field=models.JSONField(),
        ),
    ]
