# Generated by Django 5.1 on 2025-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_routing_totalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='custom_view_name',
            field=models.CharField(blank=True, help_text="Django view name to use if section_mode is 'custom'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_mode',
            field=models.CharField(choices=[('single', 'One question per page'), ('multi', 'All questions on one page'), ('flexible', 'Flexible layout'), ('custom', 'Custom section with bespoke view')], default='flexible', help_text='Controls how this section is rendered', max_length=10),
        ),
    ]
